apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: anchor-monitor
data:
  default.conf: |-
    server {
      resolver 8.8.8.8 ipv6=off;
      listen 8080 default_server;
      server_name anchor.factomd.com;
      if ($http_x_forwarded_proto = "http") {
        return 301 https://$host$request_uri;
      }
      lua_ssl_trusted_certificate  /etc/ssl/certs/ca-bundle.crt;
      set $ngo_client_id         "48298444655-98uaj4hqbcvgpdsb51rqvqeq65584aaj.apps.googleusercontent.com";
      set $ngo_client_secret   "J6WFEskQID5ypeArCtubsSWK";
      set $ngo_domain          "factom.com";
      set $ngo_token_secret      "a ljashdkljalsjfaljhfvery long randomish string";
      #set $ngo_secure_cookies    "true";
      #set $ngo_http_only_cookies "true";

      location /health {
        return 200 'Healthy!';
      }
     
      access_by_lua_file "/etc/nginx/lua/nginx-google-oauth/access.lua";
      location / {
        if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' '*';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           #
           # Custom headers and headers various browsers *should* be OK with but aren't
           #
           add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,access-control-allow-origin';
           #
           # Tell client that this pre-flight info is valid for 20 days
           #
           add_header 'Access-Control-Max-Age' 1728000;
           add_header 'Content-Type' 'text/plain; charset=utf-8';
           add_header 'Content-Length' 0;
           return 204;
        }
        if ($request_method = 'POST') {
           add_header 'Access-Control-Allow-Origin' '*';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,access-control-allow-origin';
           add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }
        if ($request_method = 'GET') {
           add_header 'Access-Control-Allow-Origin' '*';
           add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
           add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,access-control-allow-origin';
           add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }

          proxy_set_header HOST lvh.me;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://anchor-monitor-0.anchor-monitor:3000;
      }
    }
